---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    driver_config:
      network:
        - ["forwarded_port", {guest: 80, host: 8080}]

suites:
  - name: default
    run_list:
      - recipe[aar::default]
    attributes:
